version: "3"
services:
  database:
    image: postgres:17.1-alpine
    container_name: database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beleg
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
    networks:
      - application

  backend:
    build: .
    container_name: beleg-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/beleg
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      - application

networks:
  application:
    driver: bridge
volumes:
  db:
